#
# This is free software, lisence use MIT.
#
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
#
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: 上游源码同步

on:
# 定时触发
  schedule:
    - cron: 0 20 * * *

# 编辑触发
  push:
    branches:
      - master

# 点赞触发
  watch:
    types: [started]

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:

    - name: 效验本地文件
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: 设置git身份
      run : |
        git config --global user.email "claymor3.sky@gmail.com"
        git config --global user.name "ClayMoreBoy"

    - name: 加载上游提交
      run: git pull https://github.com/fw876/helloworld.git --no-edit --strategy-option ours

    - name: 推送上游提交
      env:
        DOWNSTREAM_BRANCH: master
      run: git push origin $DOWNSTREAM_BRANCH
